Python safety
simplybusiness/Kiln pull request #279
Opened 2020-12-17 12:42 UTC by DM-sb

# What does this PR change?
It introduces support for the python Safety dependency checker into report parser.

# Why is it important?
Python projects can be checked for dependencies on vulnerable packages.

# Checklist
- [x] Tests added/updated as appropriate
- [ ] Documentation added/updated as appropriate

If this PR introduces a new tool:
- [ ] Documentation on how to handle false positives added
- [ ] Documentation on how to configure the tool added

2021-01-25 13:21 UTC, DanHatesNumbers requested changes
Really pleased with how this is coming along. There's a few places where I think things can be simplified and a couple of issues where the parsing logic doesn't match up with the NIST NVD CVE schema, but really happy with the approach.

2021-01-25 13:21 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +        .iter()
```suggestion
        .flatten()
```
Types before:
![image](https://user-images.githubusercontent.com/15730032/105709289-6940cc80-5f0d-11eb-9119-e557bb500b44.png)
Types after:
![image](https://user-images.githubusercontent.com/15730032/105709304-6d6cea00-5f0d-11eb-87a3-00f26e5d8a1f.png)

2021-01-25 13:21 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +            .unwrap();
Could this be moved outside of the parsing loop so it's built once and cloned when needed?

2021-01-25 13:21 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +                    }
This will result in the values of the last entry in the `cve_vec` being used. Should we instead produce a separate DependencyEvent for each CVE attached to an advisory, defaulting to a single DependencyEvent with the pyup.io details if there aren't any associated CVEs?

2021-01-25 13:21 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +                            });
I think you could lookup the vuln once here. Additionally, `map_or` eagerly evaluates the default, so those strings are being cloned even if they're not needed, so `map_or_else` might be a better option.

2021-01-25 13:21 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +            then.status(200)
With these test cases, can we configure `head` requests to respond without the payload to closer mimic a real response?

2021-01-25 13:21 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +        assert!(events[1].advisory_url.to_string() == PYTHON_SAFETY_VULN_URL);
Could you add assertions here to check the AdvisoryId that was parsed too please?

2021-01-25 13:21 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +                    ]
Could this test data be expanded to include a package with more than one advisory in the array to cover that parsing codepath please?

2021-01-25 13:21 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +                    ]
Could this test data be expanded to include a package with more than one advisory in the array to cover that parsing codepath please?

2021-01-25 23:03 UTC, DM-sb commented on report-parser/src/main.rs
> +    "https://github.com/pyupio/safety-db/blob/master/data/insecure_full.json";
I was using the raw url when parsing and getting data out. This was being used only to print the advisory URL in case where a URL may not be available for an advisory. But I have gone ahead and replaced this with the raw URL as well.

2021-01-25 23:04 UTC, DM-sb commented on report-parser/src/main.rs
> +            .to_string();
I was using the raw url when parsing and getting data out. This was being used only to print the advisory URL in case where a URL may not be available for an advisory. But I have gone ahead and replaced this with the raw URL as well.

2021-02-12 11:48 UTC, DanHatesNumbers requested changes
Couple of small changes I'd like to see, but this is nearly ready to merge

2021-02-12 11:48 UTC, DanHatesNumbers commented on tool-images/python/safety/Dockerfile
> +RUn pip install django=='1.11.22'
What are these packages needed for?

2021-02-12 11:48 UTC, DanHatesNumbers commented on tool-images/python/safety/Dockerfile
> +RUN pip install safety
Could you include a version specifier here please? That way we can attribute scan output to a specific tool version and handle breaking changes in output correctly

2021-02-12 11:48 UTC, DanHatesNumbers commented on tool-images/python/safety/entrypoint.sh
> +    /data-forwarder --tool-name=safety --tool-version=0.6.1 --tool-output-path="$FILE_NAME" --start-time="$START_TIME" --end-time="$END_TIME" --output-format=JSON --scan-env="$SCAN_ENV" --app-name="$
Once you've added a version specifier in the Dockerfile for Safety, could you please change the tool-version option to reflect the version of Safety we've pinned to?

2021-02-12 11:48 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +                    .unwrap_or("");
If the description data array doesn't contain an english description, this expression will panic because of the usage of unwrap, which I think will propagate to cause that vuln db download to fail entirely. Could you look at replacing unwrap with `then` or `and_then` to gracefully handle this edge case please?

2021-02-12 11:48 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +    let head_resp = client.head(safety_json_db_url).send()?;
```suggestion
    let head_resp = client.head(server_name).send()?;
```

2021-02-12 11:48 UTC, DanHatesNumbers commented on report-parser/src/main.rs
> +    let safety_db_resp_text = reqwest::blocking::get(safety_json_db_url)?.text()?;
```suggestion
    let safety_db_resp_text = reqwest::blocking::get(server_name)?.text()?;
```

2021-02-15 11:26 UTC, DM-sb commented on tool-images/python/safety/Dockerfile
> +RUn pip install django=='1.11.22'
Oh those we for testing Safety, looks like I removed them after committing. Will get rid of them now.

2021-02-17 18:44 UTC, DM-sb commented on report-parser/src/main.rs
> +                    .unwrap_or("");
Done. Not sure if this is the most elegant/succinct way to do this but it took me a WHILE to figure it out.

2021-02-18 16:52 UTC, DanHatesNumbers approved these changes
Looks great, lets ship it!

2021-02-23 21:54 UTC, merged